In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("/content/census-income  (1).csv")

In [3]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
df.tail()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual_income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  annual_income   32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [6]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'annual_income'],
      dtype='object')

In [7]:
df.shape

(32561, 15)

In [8]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [9]:
df.describe(include='object')

,workclass,education,marital-status,occupation,relationship,race,sex,native-country,annual_income
count,32561,32561,32561,32561,32561,32561,32561,32561,32561
unique,9,16,7,15,6,5,2,42,2
top,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,United-States,<=50K
freq,22696,10501,14976,4140,13193,27816,21790,29170,24720

In [10]:
df['annual_income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [11]:
df['annual_income'].value_counts()

annual_income
<=50K    24720
>50K      7841
Name: count, dtype: int64

#Target is categorical
#There are two target classes
#Dataset has both numerical and categorical input features
#Dataset has 32,561 rows
#We will need encoding before most sklearn models can use the categorical features
#So,Random Forest can be the best model to predict the features

In [12]:
#To rename the target column
df.rename(columns={'annual_income':'income'},inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [14]:
df['income'].shape

(32561,)

In [15]:
df['income'].dtype

dtype('O')

In [16]:
df['income'].unique()

array(['<=50K', '>50K'], dtype=object)

In [17]:
df['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [18]:
#to check for the special characters in a dataset
(df=='?').sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [21]:
(df=="?").sum().sum()

np.int64(0)

In [20]:
df=df.replace("?",np.nan)

In [22]:
(df=="?").sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [23]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(24)

In [25]:
for col in ['workclass','occupation','native-country']:
  df[col] =df[col].fillna(df[col].mode()[0])

In [26]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
columns=['hours-per-week','age','education-num','fnlwgt']
for col in columns:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outliers=df[(df[col]<lower_bound)|(df[col]>upper_bound)]
  print(col)
  print("Q1:",Q1)
  print("Q3:",Q3)
  print("IQR:",IQR)
  print("Lower Bound:",lower_bound)
  print("Upper Bound:",upper_bound)
  print("Number of Outliers:",len(outliers))

hours-per-week
Q1: 40.0
Q3: 45.0
IQR: 5.0
Lower Bound: 32.5
Upper Bound: 52.5
Number of Outliers: 9002
age
Q1: 28.0
Q3: 48.0
IQR: 20.0
Lower Bound: -2.0
Upper Bound: 78.0
Number of Outliers: 142
education-num
Q1: 9.0
Q3: 12.0
IQR: 3.0
Lower Bound: 4.5
Upper Bound: 16.5
Number of Outliers: 1193
fnlwgt
Q1: 117827.0
Q3: 236993.0
IQR: 119166.0
Lower Bound: -60922.0
Upper Bound: 415742.0
Number of Outliers: 993

In [31]:
df.shape

(32537, 15)

In [33]:
columns=['hours-per-week','age','education-num','fnlwgt']
for col in columns:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  df=df[(df[col]>=lower_bound)&(df[col]<=upper_bound)]
  print(col, ":", len(outliers))

hours-per-week : 993
age : 993
education-num : 993
fnlwgt : 993

In [34]:
#Encoding
y=df['income']
x=df.drop('income',axis=1)

In [35]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [38]:
x.select_dtypes(include='object').columns

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country'],
      dtype='object')

In [44]:
x = pd.get_dummies(x, drop_first=True, dtype=int) #pd.get_dummies is used to convert categorical columns to numerical columns

In [45]:
x.head()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Portugal,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,38,215646,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
3,53,234721,7,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,28,338409,13,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,37,284582,14,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [46]:
x.shape

(16837, 93)

In [47]:
x.dtypes

age                               int64
fnlwgt                            int64
education-num                     int64
capital-gain                      int64
capital-loss                      int64
                                  ...
native-country_Thailand           int64
native-country_Trinadad&Tobago    int64
native-country_United-States      int64
native-country_Vietnam            int64
native-country_Yugoslavia         int64
Length: 93, dtype: object

In [48]:
print(x.shape)
print(y.shape)

(16837, 93)
(16837,)

In [50]:
print(x.head())
print(y[:5])

   age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40
5   37  284582             14             0             0              40

   workclass_Local-gov  workclass_Never-worked  workclass_Private  \
0                    0                       0                  0
2                    0                       0                  1
3                    0                       0                  1
4                    0                       0                  1
5                    0                       0                  1

   workclass_Self-emp-inc  ...  native-country_Portugal  \
0                       0  ...                        0
2                       0  ...                        0
3                       0  ...                        0
4                       0  ...                        0
5                       0  ...                        0

   native-country_Puerto-Rico  native-country_Scotland  native-country_South  \
0                           0                        0                     0
2                           0                        0                     0
3                           0                        0                     0
4                           0                        0                     0
5                           0                        0                     0

   native-country_Taiwan  native-country_Thailand  \
0                      0                        0
2                      0                        0
3                      0                        0
4                      0                        0
5                      0                        0

   native-country_Trinadad&Tobago  native-country_United-States  \
0                               0                             1
2                               0                             1
3                               0                             1
4                               0                             0
5                               0                             1

   native-country_Vietnam  native-country_Yugoslavia
0                       0                          0
2                       0                          0
3                       0                          0
4                       0                          0
5                       0                          0

[5 rows x 93 columns]
[0 0 0 0 0]

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [53]:
print("x_train:", x_train.shape)
print("x_test:", x_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

x_train: (13469, 93)
x_test: (3368, 93)
y_train: (13469,)
y_test: (3368,)

In [54]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [55]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [56]:
y_pred=rf.predict(x_test)

In [57]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy score:",accuracy)

Accuracy score: 0.8470902612826603

In [58]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2373  180]
 [ 335  480]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      2553
           1       0.73      0.59      0.65       815

    accuracy                           0.85      3368
   macro avg       0.80      0.76      0.78      3368
weighted avg       0.84      0.85      0.84      3368